// ignore_for_file: avoid_print

import 'dart:io';

// Project dashboard sourced from OpenSpec changes (the current tracker).
//
// - Active:  openspec/changes/<name>/ (proposal.md + tasks.md)
// - Archived: openspec/changes/archive/<date>-<name>/
// - Progress: `- [x]` / `- [ ]` checkboxes in tasks.md
//
// Prints the dashboard and writes it to openspec/STATUS.md (generated file;
// openspec/ is gitignored so it never pollutes `git status`).
void main() {
  print('Updating OpenSpec dashboard...');

  final changesDir = Directory('openspec/changes');
  if (!changesDir.existsSync()) {
    print('No openspec/changes directory found.');
    return;
  }

  final active = <_Change>[];
  final archived = <_Change>[];
  for (final entry in changesDir.listSync().whereType<Directory>()) {
    final name = entry.path.split(Platform.pathSeparator).last;
    if (name == 'archive') {
      for (final archivedDir
          in entry.listSync().whereType<Directory>().toList()
            ..sort((a, b) => a.path.compareTo(b.path))) {
        archived.add(_readChange(archivedDir, archived: true));
      }
      continue;
    }
    active.add(_readChange(entry, archived: false));
  }
  active.sort((a, b) => a.name.compareTo(b.name));

  final buffer = StringBuffer();
  buffer.writeln('# OpenSpec Changes Dashboard');
  buffer.writeln('');
  buffer.writeln('| Change | Progress | % | Status |');
  buffer.writeln('|---|---|---|---|');
  for (final change in active) {
    buffer.writeln(
        '| ${change.name} | ${change.bar} | ${change.percent}% | ${change.status} |');
  }
  buffer.writeln('');
  buffer.writeln('## Archived (${archived.length})');
  buffer.writeln('');
  for (final change in archived) {
    buffer.writeln(
        '- ${change.name} — ${change.done}/${change.total} (${change.percent}%)');
  }
  buffer.writeln('');
  buffer.writeln(
      '_Last updated: ${DateTime.now().toString().split('.')[0]}_ (generated by scripts/project_status.dart)');

  File('openspec/STATUS.md').writeAsStringSync(buffer.toString());
  print(buffer.toString());
  print('Dashboard written to openspec/STATUS.md');
}

final _donePattern = RegExp(r'^-\s*\[x\]', caseSensitive: false);
final _openPattern = RegExp(r'^-\s*\[ \]');

_Change _readChange(Directory dir, {required bool archived}) {
  final name = dir.path.split(Platform.pathSeparator).last;
  final tasksFile = File('${dir.path}/tasks.md');
  if (!tasksFile.existsSync()) {
    return _Change(
        name: name, done: 0, total: 0, status: archived ? 'Archived' : 'Explore');
  }
  var done = 0;
  var total = 0;
  for (final line in tasksFile.readAsStringSync().split('\n')) {
    final trimmed = line.trim();
    if (_donePattern.hasMatch(trimmed)) {
      done++;
      total++;
    } else if (_openPattern.hasMatch(trimmed)) {
      total++;
    }
  }
  final status = archived
      ? 'Archived'
      : total == 0
          ? 'Explore'
          : done == total
              ? 'Complete'
              : 'On Progress';
  return _Change(name: name, done: done, total: total, status: status);
}

class _Change {
  _Change(
      {required this.name,
      required this.done,
      required this.total,
      required this.status});

  final String name;
  final int done;
  final int total;
  final String status;

  int get percent => total == 0 ? 0 : (done * 100 / total).round();

  String get bar {
    const width = 10;
    final filled = total == 0 ? 0 : (done * width / total).round();
    return '${'#' * filled}${'.' * (width - filled)}';
  }
}
