// GENERATED by kuron_config_generator — verification test for `mangafreeinfo`.
//
// Dual-mode:
//   default        : replay golden fixtures (offline, CI-safe)
//   LIVE=1 dart test : hit the real site
//
// Regenerate via: fvm dart run bin/kuron_config_generator.dart generate \
//   --url <baseUrl> --validate --live
library;

import 'dart:io';

import 'package:dio/dio.dart';
import 'package:http_mock_adapter/http_mock_adapter.dart' as mock;
import 'package:kuron_core/kuron_core.dart';
import 'package:kuron_generic/kuron_generic.dart';
import 'package:logger/logger.dart';
import 'package:test/test.dart';

import '../support/bulk_config_loader.dart';

const _sourceId = 'mangafree';
final _live = Platform.environment['LIVE'] == '1';

String? _fixture(String screen) =>
    loadBulkFixture(_sourceId, screen, live: _live);
GenericScraperAdapter _adapter(Map<String, Object?> config,
    {mock.DioAdapter? mockAdapter}) {
  final baseUrl = config['baseUrl'] as String;
  final dio = Dio(BaseOptions(
    baseUrl: baseUrl,
    connectTimeout: const Duration(seconds: 30),
    receiveTimeout: const Duration(seconds: 60),
    headers: ((config['network'] as Map?)?['headers'] as Map?)
        ?.cast<String, dynamic>(),
    validateStatus: (s) => s != null && s < 500,
  ));
  if (mockAdapter != null) {
    dio.httpClientAdapter = mockAdapter;
  }
  return GenericScraperAdapter(
    dio: dio,
    urlBuilder: GenericUrlBuilder(baseUrl: baseUrl),
    parser: GenericHtmlParser(logger: Logger(level: Level.off)),
    logger: Logger(level: Level.off),
    sourceId: config['source'] as String,
  );
}

Future<void> main() async {
  late Map<String, Object?> config;
  late GenericScraperAdapter adapter;

  // An unpublished source is not a regression: skip with the reason instead
  // of failing when no config resolves locally or from kuron-extensions.
  String? unavailable;
  try {
    config = await loadBulkConfig(_sourceId);
    adapter = _adapter(config);
  } on StateError catch (e) {
    unavailable = 'config unavailable for $_sourceId: ${e.message}';
  }

  group('$_sourceId generated 5-screen', () {
    test('home screen returns items', () async {
      final fixture = _fixture('home');
      if (fixture == null) {
        // No golden fixture and not LIVE: nothing to replay offline.
        markTestSkipped('no home fixture for $_sourceId; re-run with LIVE=1');
        return;
      }
      // Offline replay: assert the saved home HTML still parses into items
      // through the same parser the adapter uses.
      expect(fixture, contains('<html'), reason: 'home fixture sanity');
      final result = await adapter.search(
        const SearchFilter(query: '', page: 1),
        config,
      );
      expect(result.items, isNotEmpty, reason: 'home items');
      expect(result.items.first.id, isNotEmpty);
      expect(result.items.first.title, isNotEmpty);
      for (final item in result.items) {
        expect(item.coverUrl.startsWith('http'), isTrue,
            reason: 'cover must be absolute: ${item.coverUrl}');
      }
    }, timeout: const Timeout(Duration(seconds: 90)));

    test('search screen returns results', () async {
      final result = await adapter.search(
        const SearchFilter(query: 'a', page: 1),
        config,
      );
      expect(result.items, isNotEmpty, reason: 'search "a"');
    }, timeout: const Timeout(Duration(seconds: 90)));

    test('detail screen parses title and pages/chapters', () async {
      final home = await adapter.search(
        const SearchFilter(query: '', page: 1),
        config,
      );
      final id = home.items.first.id;
      final detail = await adapter.fetchDetail(id, config);
      expect(detail.content.title, isNotEmpty, reason: 'detail title for $id');
      final hasPages = detail.content.pageCount > 0 ||
          detail.imageUrls.isNotEmpty ||
          (detail.content.chapters?.isNotEmpty ?? false);
      expect(hasPages, isTrue, reason: 'detail has pages or chapters');
    }, timeout: const Timeout(Duration(seconds: 90)));

    test('chapters + reader images resolve', () async {
      final home = await adapter.search(
        const SearchFilter(query: '', page: 1),
        config,
      );
      final detail = await adapter.fetchDetail(home.items.first.id, config);
      final chapters = detail.content.chapters;
      if (chapters == null || chapters.isEmpty) {
        // Gallery-only source (hentaifoxCdn): reader images come from the
        // detail page itself — probe reader with the content id.
        final data =
            await adapter.fetchChapterImages(home.items.first.id, config);
        expect(data?.images, isNotEmpty, reason: 'gallery reader images');
      } else {
        final data =
            await adapter.fetchChapterImages(chapters.first.id, config);
        expect(data?.images, isNotEmpty, reason: 'reader images');
      }
    }, timeout: const Timeout(Duration(seconds: 120)));
  }, skip: unavailable);
}
